In [ ]:
import pandas as pd
dados = pd.read_csv('/content/dados2704.csv', index_col=False)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21352 entries, 0 to 21351
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   TipoTomador                21352 non-null  int64
 1   ReceitaBrutaMensal         21352 non-null  float64
 2   ValorTotaBem               21352 non-null  float64
 3   AnoEntrada                 21352 non-null  int64
 4   AnoContratacao             21352 non-null  int64
 5   MesContratacao             21352 non-null  int64
 6   QuantidadeParcelas         21352 non-null  int64
 7   TotalContratacoes          21352 non-null  int64
 8   TotalContratacoesAtraso    21352 non-null  int64
 9   ValorContratado            21352 non-null  float64
 10  AtividadeRenda             21352 non-null  int64
 11  CodigoIBGE                 21352 non-null  int64
 12  Alvo                       21352 non-null  int64
 13  IBC                        21352 non-null  float64
 14  IDHM                       21352 non-null  float64
 15  participacao               21352 non-null  float64
 16  MediaMovelEmpregabilidade  21352 non-null  float64
 17  TempoRelacionamento        21352 non-null  int64
dtypes: float64(7), int64(11)
memory usage: 2.9 MB

Incluindo a variável  TaxaAtrasoAjustada

In [ ]:
dados['TaxaAtrasoAjustada'] = (
    dados['TotalContratacoesAtraso'] /
    (dados['TotalContratacoes'] + 1)
)

Incluindo a variável  ComprometimentoParcelaRenda

In [ ]:
dados['ParcelaMensalEstimada'] = (
    dados['ValorContratado'] /
    dados['QuantidadeParcelas']
)



dados['ComprometimentoParcelaRenda'] = (
                                        dados['ParcelaMensalEstimada'] /
                                        dados['ReceitaBrutaMensal']
                                    )

Incluindo a variável RiscoFinanceiro

In [ ]:
dados['RiscoFinanceiro'] = (
    dados['ComprometimentoParcelaRenda'] *
    dados['TaxaAtrasoAjustada']
)

In [ ]:
dados

,TipoTomador,ReceitaBrutaMensal,ValorTotaBem,AnoEntrada,AnoContratacao,MesContratacao,QuantidadeParcelas,TotalContratacoes,TotalContratacoesAtraso,ValorContratado,...,Alvo,IBC,IDHM,participacao,MediaMovelEmpregabilidade,TempoRelacionamento,TaxaAtrasoAjustada,ParcelaMensalEstimada,ComprometimentoParcelaRenda,RiscoFinanceiro
0,1,1914.64,205318.75,2010,2018,4,3,167,2,25140.00,...,1,73.53,0.758,0.05642,-2.394970,8,0.011905,8380.000000,4.376802,0.052105
1,1,7617.96,17464.79,2008,2009,1,5,23,1,99637.46,...,0,73.53,0.758,0.05642,-2.394970,1,0.041667,19927.492000,2.615857,0.108994
2,2,633021.72,947970.39,2008,2009,2,22,162,0,470505.43,...,0,73.53,0.758,0.05642,-2.394970,1,0.000000,21386.610455,0.033785,0.000000
3,2,860591.42,293161.24,2008,2009,1,20,143,0,434845.28,...,0,73.53,0.758,0.05642,-2.394970,1,0.000000,21742.264000,0.025264,0.000000
4,1,2725.22,142801.53,2016,2017,6,4,47,0,36147.89,...,0,73.53,0.758,0.05642,-2.394970,1,0.000000,9036.972500,3.316052,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21347,1,23608.30,435829.36,2016,2025,3,6,12,0,35387.57,...,0,53.53,0.676,0.01744,0.722988,9,0.000000,5897.928333,0.249824,0.000000
21348,2,148280.55,1215699.36,2009,2012,4,3,41,0,42587.15,...,0,53.53,0.676,0.01744,0.722988,3,0.000000,14195.716667,0.095736,0.000000
21349,1,16871.98,373427.89,2008,2008,4,12,48,0,219151.23,...,0,53.53,0.676,0.01744,0.722988,0,0.000000,18262.602500,1.082422,0.000000
21350,2,172918.46,74294.39,2019,2019,5,7,32,1,95820.19,...,0,53.53,0.676,0.01744,0.722988,0,0.030303,13688.598571,0.079162,0.002399
21351,1,19835.35,95870.30,2013,2020,6,25,44,10,388379.48,...,1,53.53,0.676,0.01744,0.722988,7,0.222222,15535.179200,0.783207,0.174046

In [ ]:
correlacoes = dados.corr(numeric_only=True)['Alvo'].sort_values(ascending=False)

print(correlacoes)

Alvo                           1.000000
TotalContratacoesAtraso        0.409540
TaxaAtrasoAjustada             0.211733
QuantidadeParcelas             0.184177
IBC                            0.115368
participacao                   0.092281
MesContratacao                 0.073543
IDHM                           0.070300
RiscoFinanceiro                0.053909
AnoEntrada                     0.024786
AtividadeRenda                 0.000370
TipoTomador                   -0.006518
ReceitaBrutaMensal            -0.037243
AnoContratacao                -0.042609
ValorContratado               -0.046163
ComprometimentoParcelaRenda   -0.048191
TempoRelacionamento           -0.060299
TotalContratacoes             -0.083005
ValorTotaBem                  -0.086490
ParcelaMensalEstimada         -0.086861
MediaMovelEmpregabilidade     -0.128144
CodigoIBGE                    -0.175769
Name: Alvo, dtype: float64

In [ ]:
novas_features = [
    'TaxaAtrasoAjustada',
    'ComprometimentoParcelaRenda',
    'RiscoFinanceiro'
]

variaveis_analise = [
    'ValorContratado',
    'ReceitaBrutaMensal',
    'QuantidadeParcelas',
    'TotalContratacoes',
    'TotalContratacoesAtraso'
] + novas_features

matriz = dados[variaveis_analise].corr()

matriz

,ValorContratado,ReceitaBrutaMensal,QuantidadeParcelas,TotalContratacoes,TotalContratacoesAtraso,TaxaAtrasoAjustada,ComprometimentoParcelaRenda,RiscoFinanceiro
ValorContratado,1.000000,0.403595,0.449954,0.218784,0.026700,0.039964,0.250844,0.161851
ReceitaBrutaMensal,0.403595,1.000000,0.161065,0.194572,0.012228,0.011720,-0.233416,-0.084466
QuantidadeParcelas,0.449954,0.161065,1.000000,0.223903,0.050373,-0.012154,0.088423,0.036627
TotalContratacoes,0.218784,0.194572,0.223903,1.000000,-0.034938,-0.216003,0.063723,-0.076259
TotalContratacoesAtraso,0.026700,0.012228,0.050373,-0.034938,1.000000,0.463802,-0.077368,0.080894
TaxaAtrasoAjustada,0.039964,0.011720,-0.012154,-0.216003,0.463802,1.000000,-0.034917,0.376589
ComprometimentoParcelaRenda,0.250844,-0.233416,0.088423,0.063723,-0.077368,-0.034917,1.000000,0.307743
RiscoFinanceiro,0.161851,-0.084466,0.036627,-0.076259,0.080894,0.376589,0.307743,1.000000

In [ ]:
dados.to_csv('/content/dados2505.csv', index=False)